"""Generate Elixir test data from the shared JSON vectors; CI checks for drift."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def elixir(value):
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, dict):
        return "%{" + ", ".join(elixir(k)+" => "+elixir(v) for k,v in value.items()) + "}"
    if isinstance(value, list):
        return "[" + ", ".join(elixir(v) for v in value) + "]"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False).replace("#{", "\\#{")
    return json.dumps(value, allow_nan=False)

cases = json.loads((ROOT / "fixtures/contract_cases.json").read_text(encoding="utf-8"))
(ROOT / "fixtures/contract_vectors.exs").write_text(
    "# Generated by tools/generate_contract_vectors.py; CI checks for drift.\n"+elixir(cases)+"\n",
    encoding="utf-8")
